### ISSUE TITLE
Step 5: Install Certificate Error: Certificate signature failed. "status":400

### ISSUE THREAD

**Issue by ti-ka** [diafygi/gethttpsforfree#78] opened 2016-02-11 21:06 UTC
**Seriously start at Step 1?**

> Step 5: Install Certificate (Error: Certificate signature failed. Please start back at Step 1. {"type":"urn:acme:error:malformed","detail":"Error creating new cert :: Certificate public key must be different than account key","status":400})

<img width="1432" alt="screen shot 2016-02-11 at 3 04 29 pm" src="https://cloud.githubusercontent.com/assets/5960121/12990621/f73e1e32-d0d0-11e5-9fda-2d5e4cdcee66.png">

I have different keys for public and private.

<img width="621" alt="screen shot 2016-02-11 at 3 11 52 pm" src="https://cloud.githubusercontent.com/assets/5960121/12990790/d16bda72-d0d1-11e5-972a-bc3dfb46b621.png">

**Comment by qsantos** [comment] 2016-02-12 17:52
This is a duplicate of #13 . You need one pair of public/private keys for `account.key` and **another** key pair for `domain.key`.

That said, I agree that there should be an earlier warning, if possible (this is what brought me here). https://gethttpsforfree.com/ is a great website by the way!

**Comment by diafygi** [comment] 2016-02-22 21:36
Open to a pull request that checks the text of the two keys to see if they're the same.

**Closed as completed** 2016-06-10 16:55 UTC
